### ISSUE TITLE
pochettes choix spotify/apple music

### ISSUE THREAD

**Issue by Ryslo** [Jeremmie/punchyparasite_2#14]
ça serait pas mal que quand tu clique sur les pochettes dans l’onglet "songs" ou "pochettes" tu sois pas redirigé vers uniquement spotify 
si on veut toucher le max de monde il faudrait que quand tu clique dessus t’ai le choix d’être redirigé vers le morceau sur spotify ou apple music ! :)

**Comment by Jeremmie** [comment]
ajout de modal pop-up qui redirigent vers spotify/applemusic/youtube/deezer
