### ISSUE TITLE
plateformes = accueil 

### ISSUE THREAD

**Issue by Ryslo** [Jeremmie/punchyparasite_2#17]
la page "plateforme" serait directement accueil 
si t’as déjà changé en anglais "home" 
et c’est pas mal si t’as les deux genre l’onglet « Home » et si tu clique sur le logo t’y arrive aussi
parce que c’est vraiment la page la plus importante 
t’as genre 
- le titre (avec logo)
- la photo principale 
- les plateformes 
- les photos (du dossier "accueil") qui peuvent défiler en bas de la page

**Comment by Jeremmie** [comment]
La fenetre plateforme est devenu Home le logo ramène aussi à home
