### ISSUE TITLE
logo sur home a centrer

### ISSUE THREAD

**Issue by Ryslo** [Jeremmie/punchyparasite_2#26]
le logo dans "want to take a look" est pas vraiment centré il faudrait que le corps du logo soit centré et pas le tout

**Comment by Jeremmie** [comment]
décision d'enlever l'image background

**Comment by Ryslo** [comment]
pour la version ordi le logo est toujours pas centré on faudrait centré par rapport au corps et pas pr rapport a l’i

Uploading 68616455053__80B3215F-A4B3-43CD-9D88-606A18154FD2.MOV…

mage entière
